# Kartanalys ("Hitta ställen"): the button bottom right (where "uppdatera" was) opens one
# panel with every map analysis -- depth range, steep edges, tops & holes, vegetation edge,
# hard bottom, wind edge, "like my spot", and presets (Abborre/Gädda/Gös). What matches is
# lit, the rest toned down; "Kartanalys" in Filter shows/hides it; remembered per lake.
from playwright.sync_api import sync_playwright
import fakefb, json
from fakefb import new_page
import test_weather as _tw
results = []
def check(name, cond, info=''):
    results.append(bool(cond)); print(('PASS ' if cond else 'FAIL ') + name + ('  -- ' + str(info) if info != '' else ''))
B3 = (58.887269, 15.772629)                      # on Regnaren's water (south basin)
cfg = {'waypoints': [{'lat': 58.88651, 'lon': 15.777774, 'name': 'Djupa hålet', 'uid': 'filip', 'by': 'Filip', 'type': 'abborre'}]}

def an(pg): return pg.evaluate('window.__ffAnalysis()')
CAT = {'abborre': 'rule', 'gadda': 'rule', 'gos': 'rule', 'similar': 'similar'}
def pick(pg, m, wait=1300):
    # the category first (the row on top), then the choice in it (Liknande: the category is the choice)
    pg.click('#anCatSeg button[data-cat="%s"]' % CAT.get(m, 'map')); pg.wait_for_timeout(150)
    if m != 'similar': pg.click('#anPanel button[data-m="%s"]' % m)
    pg.wait_for_timeout(wait); return an(pg)
def lit(pg):
    return pg.evaluate("""() => { var c = document.getElementById('anLayer'); if (!c.classList.contains('on')) return 0;
      var d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data, n = 0; for (var i = 3; i < d.length; i += 4) if (d[i] > 0) n++; return n; }""")

with sync_playwright() as p:
    b, ctx, pg, errs = new_page(p, geo=B3, cfg=cfg, name=None)
    wx = _tw.wx_json(); wx['current']['wind_speed_10m'] = 6; wx['current']['wind_direction_10m'] = 225
    ctx.route('**/api.open-meteo.com/**', lambda r: r.fulfill(status=200, content_type='application/json', body=json.dumps(wx), headers={'Access-Control-Allow-Origin': '*'}))
    pg.evaluate("localStorage.removeItem('ffmap_weather_v1')"); pg.reload(); pg.wait_for_timeout(600); fakefb.login(pg, 'Filip'); pg.wait_for_timeout(2500)
    check('the analysis button is where "uppdatera" was; that one is gone', pg.is_visible('#anBtn') and pg.query_selector('#refreshBtn') is None)
    pg.click('#visMoreBtn'); pg.wait_for_timeout(200)
    check('Filter: "Kartanalys" (on) and "Håll skärmen tänd" (off)', pg.is_checked('#toggleAnalysis') and not pg.is_checked('#toggleWake'))
    pg.click('#visMoreBtn'); pg.wait_for_timeout(200)
    check('nothing chosen yet: nothing drawn', an(pg)['mode'] is None and lit(pg) == 0)
    pg.click('#anBtn'); pg.wait_for_timeout(400)
    cats = pg.eval_on_selector_all('#anCatSeg button', 'e => e.map(x => x.textContent)')
    chips = pg.eval_on_selector_all('#anChips button', 'e => e.map(x => x.textContent)') + pg.eval_on_selector_all('#anPresets button[data-m]', 'e => e.map(x => x.textContent)')
    check('the panel: categories on top (Kartdata / Tumregler / Fångster / Liknande), Kartdata shown', cats == ['Kartdata', 'Tumregler', 'Fångster', 'Liknande'] and pg.is_visible('#anChips') and not pg.is_visible('#anPresets'), cats)
    check('...every analysis + the rules of thumb', chips == ['Djup', 'Branta kanter', 'Grynnor & hålor', 'Växter', 'Hård botten', 'Vindkant', 'Abborre', 'Gädda', 'Gös'], chips)
    pg.click('#anCatSeg button[data-cat="rule"]'); pg.wait_for_timeout(150)
    check('...Tumregler: its three, like any other button (no orange edge)', pg.is_visible('#anPresets') and not pg.is_visible('#anChips') and
          pg.eval_on_selector('#anPresets button', 'e => getComputedStyle(e).borderTopColor') == pg.eval_on_selector('#anChips button', 'e => getComputedStyle(e).borderTopColor'))
    pg.click('#anCatSeg button[data-cat="map"]'); pg.wait_for_timeout(150)
    a = pick(pg, 'depth')
    check('Djup 4–6 m: a share of the lake lit, the rest toned down', a['ready'] and a['n'] > 1000 and '4,0–6,0 m' in a['text'] and lit(pg) > 10000, a)
    n46 = a['n']
    check('the depth range: one bar in the depth colours with two handles (like the legend)', pg.is_visible('#anControls .anDual') and len(pg.query_selector_all('#anControls .anKnob')) == 2)
    r = pg.eval_on_selector('#anControls .anDual', 'e => { var r = e.getBoundingClientRect(); return [r.left, r.top, r.width, r.height]; }')
    dmax = float(pg.inner_text('#anControls .anTicks span:last-child').replace(' m', '').replace(',', '.'))
    k = pg.eval_on_selector_all('#anControls .anKnob', 'e => e.map(x => { var r = x.getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; })')[1]
    pg.mouse.move(k[0], k[1]); pg.mouse.down(); pg.mouse.move(r[0] + r[2] * 9 / dmax, k[1], steps=8); pg.mouse.up(); pg.wait_for_timeout(600)
    a = an(pg)
    check('drag the right handle to 9 m: more of the lake', a['n'] > n46 and '4,0–9,0 m' in a['text'], a['text'])
    check('no "Mörkare" in the panel any more (it is in Inställningar)', pg.query_selector('#anControls #anDim') is None and pg.input_value('#anDimSet') == '0.72')
    dark = pg.evaluate("(() => { var c = document.getElementById('anLayer'); return c.getContext('2d').getImageData(5, 5, 1, 1).data[3]; })()")
    pg.evaluate("(() => { var e = document.getElementById('anDimSet'); e.value = 0.4; e.dispatchEvent(new Event('input', { bubbles: true })); })()"); pg.wait_for_timeout(300)
    light = pg.evaluate("(() => { var c = document.getElementById('anLayer'); return c.getContext('2d').getImageData(5, 5, 1, 1).data[3]; })()")
    check('Inställningar "Mörkare" (72 % from start): lighter when turned down', light < dark - 40, (dark, light))
    pg.evaluate("(() => { var e = document.getElementById('anDimSet'); e.value = 0.72; e.dispatchEvent(new Event('input', { bubbles: true })); })()")
    check('the rest of the map is also greyed (a saturation layer)', pg.evaluate("getComputedStyle(document.getElementById('anSat')).mixBlendMode") == 'saturation' and pg.is_visible('#anSat'))
    pg.screenshot(path='shot_an_depth.png')
    shore = pg.evaluate("""() => { var c = document.getElementById('anLayer'), d = c.getContext('2d').getImageData(0, 0, c.width, c.height).data, n = 0;
      for (var i = 0; i < d.length; i += 4) if (d[i] > 235 && d[i + 1] > 235 && d[i + 2] > 235 && d[i + 3] > 90 && d[i + 3] < 170) n++; return n; }""")
    check('the lake outline: a thin solid (smooth) white line at ~50 %', shore > 150, shore)
    a = pick(pg, 'steep'); check('Branta kanter: steep parts found', a['ready'] and a['n'] > 100, a)
    a = pick(pg, 'tops'); check('never called "topp"; the labels are just the depth ("2,4 m")', a['labels'] and pg.evaluate("[].every.call(document.querySelectorAll('.anLbl:not(.sim):not(.simRef)'), e => /^\d+(,\d)? m$/.test(e.textContent))") and 'topp' not in pg.inner_text('#anPanel').lower())
    a = an(pg); check('Grynnor & hålor (prominence: how far they rise above the saddle): labelled on the map', a['ready'] and a['labels'] >= 4 and 'reser sig minst 0,6 m' in a['text'], a)
    def setr(i, v): pg.evaluate("([i, v]) => { var e = document.getElementById(i); e.value = v; e.dispatchEvent(new Event('input', { bubbles: true })); }", [i, v])
    setr('anTopP', 2.0); setr('anHoleP', 2.0); pg.wait_for_timeout(900)
    a2 = an(pg); check('sliders for how much higher / lower: stricter = fewer', a2['labels'] < a['labels'], (a['labels'], a2['labels']))
    check('the panel explains what a grynna and a håla are', 'Grynna' in pg.inner_text('#anResult') and 'Håla' in pg.inner_text('#anResult') and 'sadeln' in pg.inner_text('#anResult'))
    setr('anTopP', 0.6); setr('anHoleP', 0.8); pg.wait_for_timeout(900)
    lbl = pg.query_selector('.anLbl')
    pg.evaluate("document.querySelector('.anLbl').click()"); pg.wait_for_timeout(600)
    check('tap a label: the lead line is dropped there, the panel closes', pg.eval_on_selector('#probe', 'e => e.classList.contains("show")') and not pg.eval_on_selector('#anPanel', 'e => e.classList.contains("show")'))
    pg.click('#anBtn'); pg.wait_for_timeout(300)
    a = pick(pg, 'veg', 2500); check('Växter: where there is vegetation (Genesis, fetched when needed), no sliders', a['ready'] and a['n'] > 50 and not pg.query_selector('#anControls .anDual'), a)
    a = pick(pg, 'hard'); check('Hård botten', a['ready'] and a['n'] > 100, a)
    setr('anHmin', 4); pg.wait_for_timeout(700)
    a2 = an(pg); check('hard bottom: a slider for how hard (+ a depth range)', a2['n'] < a['n'] and 'Mycket hård' in a2['text'] and pg.is_visible('#anControls .anDual'), (a['n'], a2['n'], a2['text']))
    a = pick(pg, 'wind'); check('Vindkant: from the weather wind (6 m/s SV)', a['ready'] and a['n'] > 100 and 'SV' in a['text'], a)
    a = pick(pg, 'similar'); check('Liknande: like "Djupa hålet", a list of places', a['ready'] and a['list'] >= 1 and 'Djupa hålet' in a['text'], a)
    pg.screenshot(path='shot_an_similar.png')
    pg.click('#anResult button[data-go="1"]'); pg.wait_for_timeout(700)
    check('"Åk hit" from the list: the lead line there (no extra card)', pg.eval_on_selector('#probe', 'e => e.classList.contains("show")') and pg.query_selector('#navCard') is None)
    rt = (pg.eval_on_selector('#routeLayer .rtLine', 'e => e.getAttribute("points")') or '').split()
    onscreen = pg.evaluate("(() => { var r = document.getElementById('probe').getBoundingClientRect(), d = document.getElementById('dot') || document.querySelector('#dotArrow'); return r.left > 0 && r.left < 390 && r.top > 100 && r.top < 700; })()")
    check('...the route by water drawn, and the map shows the whole way (the place on screen)', len(rt) >= 2 and onscreen, (len(rt), onscreen))
    pg.click('#anBtn'); pg.wait_for_timeout(300)
    # the panel with a FINGER (touch events, like on the phone): only the grip strip at the top moves it
    cdp = ctx.new_cdp_session(pg)
    def touch(x, y0, y1, steps, ms):
        cdp.send('Input.dispatchTouchEvent', {'type': 'touchStart', 'touchPoints': [{'x': x, 'y': y0}]})
        for k in range(1, steps + 1):
            cdp.send('Input.dispatchTouchEvent', {'type': 'touchMove', 'touchPoints': [{'x': x, 'y': y0 + (y1 - y0) * k / steps}]}); pg.wait_for_timeout(ms)
        cdp.send('Input.dispatchTouchEvent', {'type': 'touchEnd', 'touchPoints': []}); pg.wait_for_timeout(500)
    def grip(): return pg.eval_on_selector('#anPanel .grab', 'e => { var r = e.getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2, r.width, r.height]; }')
    def panel(): return pg.eval_on_selector('#anPanel', 'e => [e.getBoundingClientRect().height, e.classList.contains("show")]')
    g = grip()
    check('the grip: a whole strip across the top, easy to hit with a finger', g[2] >= 380 and g[3] >= 26, g)
    h0 = panel()[0]
    touch(g[0] + 90, g[1], g[1] + 70, 14, 30)
    h1, open1 = panel()
    check('drag the grip down slowly (finger): smaller, still open', open1 and h1 < h0 - 50, (h0, h1))
    c = pg.eval_on_selector('#anResult', 'e => { var r = e.getBoundingClientRect(); return [r.left + 60, r.top + 10]; }')
    touch(c[0], c[1], c[1] + 60, 10, 30)
    check('drag inside the panel: no resizing (only scrolling)', abs(panel()[0] - h1) < 2 and panel()[1], (h1, panel()))
    # scrolling works when the finger starts on anything in it (a chip, a button), not just empty space
    pg.eval_on_selector('#anPanel', 'e => e.scrollTop = 0'); pg.wait_for_timeout(100)
    ch = pg.eval_on_selector('#anCatSeg button', 'e => { var r = e.getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; }')
    touch(ch[0], ch[1], ch[1] - 120, 12, 25)
    check('scrolling from a chip (finger on a button) scrolls the panel', pg.eval_on_selector('#anPanel', 'e => e.scrollTop') > 20, pg.eval_on_selector('#anPanel', 'e => e.scrollTop'))
    pg.eval_on_selector('#anPanel', 'e => e.scrollTop = 0')
    g = grip(); touch(g[0], g[1], g[1] - 200, 12, 30)
    check('drag the grip up: bigger again (at least its normal size, up to all it holds)', panel()[0] >= h0 - 3, (h0, panel()))
    g = grip(); touch(g[0], g[1], g[1] + 220, 3, 0)          # (a quick flick: ~200 px in a moment)
    check('flick the grip down: closed', not panel()[1])
    pg.click('#anBtn'); pg.wait_for_timeout(500)
    g = grip(); touch(g[0], g[1], 840, 40, 25)
    check('drag the grip all the way down: closed', not panel()[1])
    pg.click('#anBtn'); pg.wait_for_timeout(300)
    for m in ('abborre', 'gadda', 'gos'):
        a = pick(pg, m); check('preset %s: combined, says it is rules of thumb' % m, a['ready'] and a['n'] > 50 and 'Tumregler' in pg.inner_text('#anResult'), a)
    # Filter shows/hides it (keeps the choice)
    pg.click('#anClose'); pg.wait_for_timeout(200)
    pg.click('#visMoreBtn'); pg.wait_for_timeout(200); pg.click('label:has(#toggleAnalysis) .toggle'); pg.click('#visMoreBtn'); pg.wait_for_timeout(300)
    check('Filter "Kartanalys" off: hidden, choice kept', lit(pg) == 0 and an(pg)['mode'] == 'gos')
    pg.click('#visMoreBtn'); pg.wait_for_timeout(200); pg.click('label:has(#toggleAnalysis) .toggle'); pg.click('#visMoreBtn'); pg.wait_for_timeout(300)
    check('...on again: shown', lit(pg) > 1000)
    pg.reload(); pg.wait_for_timeout(3000)
    check('after a restart of the app: Kartanalys off (no grey map)', an(pg)['mode'] is None and lit(pg) == 0, an(pg))
    pg.click('#anBtn'); pg.wait_for_timeout(300)
    check('the panel: ✕ in the grip strip; at the bottom "Stäng av kartanalys" (greyed out with nothing on) + "Återställ"', pg.is_visible('#anPanel .grab #anClose') and pg.is_disabled('#anClear') and
          pg.inner_text('#anClear') == '✕ Stäng av kartanalys' and pg.inner_text('#anReset') == '↺ Återställ' and not pg.eval_on_selector('#anClear', 'e => e.classList.contains("on")'))
    a = pick(pg, 'gos')
    check('...something chosen: "Stäng av kartanalys" active (never the amber "chosen" look)', pg.is_enabled('#anClear') and not pg.eval_on_selector('#anClear', 'e => e.classList.contains("on")'))
    pg.click('#anClear'); pg.wait_for_timeout(300)
    check('"Stäng av kartanalys": nothing chosen, nothing drawn', an(pg)['mode'] is None and lit(pg) == 0)
    # Återställ: every setting back to the start (what's on stays on)
    a = pick(pg, 'steep')
    pg.evaluate("(() => { var e = document.getElementById('anSlope'); e.value = 22; e.dispatchEvent(new Event('input', { bubbles: true })); })()"); pg.wait_for_timeout(900)
    check('a setting changed: "Återställ" can be pressed', pg.is_enabled('#anReset'))
    pg.click('#anReset'); pg.wait_for_timeout(1200)
    check('..."Återställ": back to the start (lutning 10 %), still showing Branta kanter; then greyed out', an(pg)['mode'] == 'steep' and 'över 10 %' in an(pg)['text'] and pg.is_disabled('#anReset'), an(pg)['text'])
    pg.click('#anClear'); pg.wait_for_timeout(300)
    # a spot's sheet: "Hitta liknande" opens the analysis on "Liknande" for that spot
    pg.evaluate("n => { var id = Object.keys(window.__wpDocs).filter(k => window.__wpDocs[k].name === n)[0]; document.querySelector('#waypoints [data-id=' + JSON.stringify(id) + ']').click(); }", 'Djupa hålet')
    pg.wait_for_timeout(400)
    check('a spot sheet: "Åk hit" and "Hitta liknande"', pg.is_visible('#wpGo') and pg.is_visible('#wpLike'))
    pg.click('#wpLike'); pg.wait_for_timeout(1500)
    a = an(pg)
    check('"Hitta liknande": the analysis opens on Liknande for that spot', pg.eval_on_selector('#anPanel', 'e => e.classList.contains("show")') and a['mode'] == 'similar' and 'Djupa hålet' in a['text'] and a['list'] >= 1, a)
    f = pg.eval_on_selector_all('#anSimF button', 'e => e.map(x => x.textContent + (x.classList.contains("on") ? "+" : ""))')
    r = pg.eval_on_selector_all('#anSimR button', 'e => e.map(x => x.textContent + (x.classList.contains("on") ? "+" : ""))')
    check('Liknande: choose what to compare (all on) and the area (right under the spot by default)', f == ['Djup+', 'Lutning+', 'Botten+', 'Växter+', 'Grynna/håla+'] and r[0] == 'Bara platsen+', (f, r))
    check('...with what "area" means (the average within the radius)', 'snittet' in pg.inner_text('#anControls .anNote'))
    check('...the spot itself: a pink ring spreading out round it', pg.query_selector('.anLbl.simRef') is not None)
    pg.click('#anRefGo'); pg.wait_for_timeout(1200)
    pos = pg.evaluate("(() => { var r = document.querySelector('.anLbl.simRef').getBoundingClientRect(); return [r.left, r.top]; })()")
    check('"Gå till": the map goes to the spot (panel closed)', not pg.eval_on_selector('#anPanel', 'e => e.classList.contains("show")') and abs(pos[0] - 195) < 60 and abs(pos[1] - 422) < 120, pos)
    pg.click('#anBtn'); pg.wait_for_timeout(500)
    pg.click('#anSimR button[data-r="50"]'); pg.wait_for_timeout(2500)
    a2 = an(pg); check('...50 m round it', 'inom 50 m' in a2['text'] and a2['list'] >= 1, a2)
    pg.click('#anSimF button[data-f="h"]'); pg.wait_for_timeout(1200)
    a3 = an(pg); check('...without the bottom: not compared any more', 'botten' not in a3['text'].split(':', 1)[1].replace('jämn botten', ''), a3['text'])
    for k in 'dsvt': pg.click('#anSimF button[data-f="%s"]' % k); pg.wait_for_timeout(200)
    pg.wait_for_timeout(1200)
    check('...nothing chosen: says to choose something', 'Välj minst en' in an(pg)['text'])
    check('no page errors', not errs, errs)
    b.close()
# turning the phone (the home-screen app reloads the page): Kartanalys stays on
with sync_playwright() as p:
    b = p.chromium.launch(**fakefb.LAUNCH)
    ctx = b.new_context(viewport={'width': 390, 'height': 844}, has_touch=True, is_mobile=True, geolocation={'latitude': B3[0], 'longitude': B3[1], 'accuracy': 8}, permissions=['geolocation'])
    ctx.add_init_script('window.__fakeCfg = {};')
    ctx.add_init_script("Object.defineProperty(navigator, 'standalone', { value: true, configurable: true });")
    ctx.add_init_script(fakefb.FAKE_FIREBASE_JS)
    pg = ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto('http://localhost:8899/index.html'); pg.wait_for_timeout(500); fakefb.login(pg, 'Filip'); pg.wait_for_timeout(2500)
    pg.click('#anBtn'); pg.wait_for_timeout(300); pick(pg, 'depth'); pg.click('#anClose'); pg.wait_for_timeout(300)
    pg.evaluate("window.__rc = 1")
    pg.set_viewport_size({'width': 844, 'height': 390})
    pg.evaluate("window.dispatchEvent(new Event('orientationchange')); if (screen.orientation) screen.orientation.dispatchEvent(new Event('change'));")
    pg.wait_for_load_state('load'); pg.wait_for_timeout(3500)
    check('turning the phone (reload): Kartanalys still on and drawn', pg.evaluate('window.__rc') is None and an(pg)['mode'] == 'depth' and an(pg)['ready'] and lit(pg) > 1000, an(pg))
    check('no page errors', not errs, errs)
    b.close()
print('\n%d/%d passed' % (sum(results), len(results)))
